# **1. Import Libraries & Load Data**

In [45]:
import pandas as pd
import numpy as np

In [46]:
datasets = {}

for year in range(2020, 2025):
    file = f"ttc-bus-delay-data-{year}.xlsx"
    sheets = pd.read_excel(file, sheet_name=None)

    datasets[year] = pd.concat(
        sheets.values(), ignore_index=True
    )

datasets[2025] = pd.read_csv(
    "TTC Bus Delay Data since 2025.csv",
    low_memory=False
)

# Display dataset dimensions
for year, df in datasets.items():
    print(f"{year}: {df.shape[0]} rows, {df.shape[1]} columns")

2020: 36151 rows, 13 columns
2021: 42269 rows, 13 columns
2022: 58707 rows, 10 columns
2023: 56207 rows, 10 columns
2024: 59643 rows, 10 columns
2025: 102257 rows, 11 columns

# **2. Data Inspection**

In [47]:
for year, df in datasets.items():
    print(f"\nYear {year}:")
    print(df.columns.tolist())

Year 2020:
['Report Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Delay', 'Gap', 'Direction', 'Vehicle', 'Date', 'Min Delay', 'Min Gap']

Year 2021:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle', 'Line', 'Bound', 'Unnamed: 10']

Year 2022:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle']

Year 2023:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle']

Year 2024:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle']

Year 2025:
['_id', 'Date', 'Line', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Vehicle']

In [48]:
for year, df in datasets.items():
    print(f"\n========== YEAR {year} ==========")
    display(df.head(5))

========== YEAR 2020 ==========

,Report Date,Route,Time,Day,Location,Incident,Delay,Gap,Direction,Vehicle,Date,Min Delay,Min Gap
0,2020-01-01,94.0,00:01:00,Wednesday,Ossington station and Castle Frank Station,General Delay,10.0,20.0,B/W,NaN,NaT,NaN,NaN
1,2020-01-01,320.0,01:31:00,Wednesday,Yonge @ Queen,Diversion,1.0,1.0,B/W,NaN,NaT,NaN,NaN
2,2020-01-01,29.0,01:37:00,Wednesday,Dufferin loop,Mechanical,8.0,14.0,N/B,9028.0,NaT,NaN,NaN
3,2020-01-01,102.0,01:40:00,Wednesday,Warden station,Mechanical,11.0,22.0,N/B,8504.0,NaT,NaN,NaN
4,2020-01-01,68.0,01:42:00,Wednesday,Warden Station,Mechanical,8.0,23.0,N/B,8721.0,NaT,NaN,NaN

========== YEAR 2021 ==========

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle,Line,Bound,Unnamed: 10
0,2021-01-01,320,04:26,Friday,YONGE AND STEELES,Emergency Services,0,0,N,1553,NaN,NaN,NaN
1,2021-01-01,63,05:04,Friday,CANNIFF AND STRACHAN,Mechanical,10,0,N,8144,NaN,NaN,NaN
2,2021-01-01,42,05:34,Friday,WILSON GARAGE,Mechanical,24,48,N,8365,NaN,NaN,NaN
3,2021-01-01,320,05:44,Friday,YONGE AND STEELES,Emergency Services,15,30,N,8181,NaN,NaN,NaN
4,2021-01-01,35,06:21,Friday,JANE STATION,Vision,30,60,E,3186,NaN,NaN,NaN

========== YEAR 2022 ==========

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle
0,2022-01-01,320,02:00,Saturday,YONGE AND DUNDAS,General Delay,0,0,NaN,8531
1,2022-01-01,325,02:00,Saturday,OVERLEA AND THORCLIFFE,Diversion,131,161,W,8658
2,2022-01-01,320,02:00,Saturday,YONGE AND STEELES,Operations - Operator,17,20,S,0
3,2022-01-01,320,02:07,Saturday,YONGE AND STEELES,Operations - Operator,4,11,S,0
4,2022-01-01,320,02:13,Saturday,YONGE AND STEELES,Operations - Operator,4,8,S,0

========== YEAR 2023 ==========

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle
0,2023-01-01,91,02:30,Sunday,WOODBINE AND MORTIMER,Diversion,81,111,NaN,8772
1,2023-01-01,69,02:34,Sunday,WARDEN STATION,Security,22,44,S,8407
2,2023-01-01,35,03:06,Sunday,JANE STATION,Cleaning - Unsanitary,30,60,N,1051
3,2023-01-01,900,03:14,Sunday,KIPLING STATION,Security,17,17,NaN,3334
4,2023-01-01,85,03:43,Sunday,MEADOWALE LOOP,Security,1,1,NaN,1559

========== YEAR 2024 ==========

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle
0,2024-01-01,89,02:08,Monday,KEELE AND GLENLAKE,Vision,10,20,N,7107
1,2024-01-01,39,02:30,Monday,FINCH STATION,General Delay,20,40,NaN,8914
2,2024-01-01,300,03:13,Monday,BLOOR AND MANNING,General Delay,0,0,NaN,8562
3,2024-01-01,65,03:23,Monday,PARLIAMENT AND BLOOR,Security,0,0,N,8574
4,2024-01-01,113,03:37,Monday,MAIN STATION,Security,0,0,NaN,8541

========== YEAR 2025 ==========

,_id,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle
0,1,2025-01-01T00:00:00,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442
1,2,2025-01-01T00:00:00,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,NaN,0
2,3,2025-01-01T00:00:00,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,NaN,8546
3,4,2025-01-01T00:00:00,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693
4,5,2025-01-01T00:00:00,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801

# **3. Data Integration & Standardization**

In [49]:
df_2020 = datasets[2020].copy()

df_2020['Date'] = df_2020['Date'].combine_first(
    df_2020['Report Date']
)

df_2020['Min Delay'] = df_2020['Min Delay'].combine_first(
    df_2020['Delay']
)

df_2020['Min Gap'] = df_2020['Min Gap'].combine_first(
    df_2020['Gap']
)

# Remove redundant columns
df_2020 = df_2020.drop(
    columns=['Report Date', 'Delay', 'Gap']
)

datasets[2020] = df_2020

print("2020 columns standardized successfully!")
print("\nUpdated columns:")
print(df_2020.columns.tolist())

print("\nDataset shape:", df_2020.shape)

2020 columns standardized successfully!

Updated columns:
['Route', 'Time', 'Day', 'Location', 'Incident', 'Direction', 'Vehicle', 'Date', 'Min Delay', 'Min Gap']

Dataset shape: (36151, 10)

In [50]:
# df_2021 = datasets[2021].copy()

# extra_columns = ['Line', 'Bound', 'Unnamed: 10']

# for col in extra_columns:
#     print(f"\nColumn: {col}")
#     print("Non-missing values:", df_2021[col].notna().sum())
#     print("Missing values:", df_2021[col].isna().sum())
#     print("Sample values:")
#     print(df_2021[col].dropna().head(5).tolist())

Column: Line
Non-missing values: 2291
Missing values: 39978
Sample values:
[510, 310, 504, 506, 504]

Column: Bound
Non-missing values: 2013
Missing values: 40256
Sample values:
['N', 'N', 'N', 'W', 'N']

Column: Unnamed: 10
Non-missing values: 1
Missing values: 42268
Sample values:
['eglinton east expr']

In [51]:
# df_2021 = datasets[2021]

# print("Route and Line:")
# print("Both filled:",
#       (df_2021['Route'].notna() & df_2021['Line'].notna()).sum())

# print("Only Line filled:",
#       (df_2021['Route'].isna() & df_2021['Line'].notna()).sum())

# print("\nDirection and Bound:")
# print("Both filled:",
#       (df_2021['Direction'].notna() & df_2021['Bound'].notna()).sum())

# print("Only Bound filled:",
#       (df_2021['Direction'].isna() & df_2021['Bound'].notna()).sum())

# print("\nRow containing Unnamed: 10:")
# display(df_2021[df_2021['Unnamed: 10'].notna()])

Route and Line:
Both filled: 0
Only Line filled: 2291

Direction and Bound:
Both filled: 0
Only Bound filled: 2013

Row containing Unnamed: 10:

,Date,Route,Time,Day,Location,Incident,Min Delay,Min Gap,Direction,Vehicle,Line,Bound,Unnamed: 10
40063,2021-12-23,20,13:27,Thursday,DANFORTH AND LEYTON,Operations - Operator,20,40,W,8518,NaN,NaN,eglinton east expr

In [52]:
df_2021 = datasets[2021].copy()

# Combine Route and Line
df_2021['Route'] = df_2021['Route'].combine_first(
    df_2021['Line']
)

# Combine Direction and Bound
df_2021['Direction'] = df_2021['Direction'].combine_first(
    df_2021['Bound']
)

# Preserve the single additional note separately
extra_note = df_2021.loc[
    df_2021['Unnamed: 10'].notna(),
    ['Date', 'Route', 'Unnamed: 10']
].copy()

# Remove redundant columns
df_2021 = df_2021.drop(
    columns=['Line', 'Bound', 'Unnamed: 10']
)

# Update dataset
datasets[2021] = df_2021

print("2021 columns standardized successfully!")

print("\nUpdated columns:")
print(df_2021.columns.tolist())

print("\nDataset shape:", df_2021.shape)

print("\nPreserved additional note:")
display(extra_note)

2021 columns standardized successfully!

Updated columns:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle']

Dataset shape: (42269, 10)

Preserved additional note:

            Date Route         Unnamed: 10
40063 2021-12-23    20  eglinton east expr

In [53]:
df_2025 = datasets[2025].copy()

df_2025['Date'] = pd.to_datetime(
    df_2025['Date'],
    errors='coerce'
)

# print("Earliest date:", df_2025['Date'].min())
# print("Latest date:", df_2025['Date'].max())

# print("\nRecords by year:")
# print(df_2025['Date'].dt.year.value_counts().sort_index())

# print("\nInvalid dates:", df_2025['Date'].isna().sum())

Earliest date: 2025-01-01 00:00:00
Latest date: 2026-08-31 00:00:00

Records by year:
Date
2025    63029
2026    39228
Name: count, dtype: int64

Invalid dates: 0

In [54]:
# Rename columns to match previous years
df_2025 = df_2025.rename(columns={
    'Line': 'Route',
    'Station': 'Location',
    'Bound': 'Direction',
    'Code': 'Incident' 
})

# Preserve original record IDs separately
df_2025 = df_2025.drop(columns=['_id'])

# Update dataset
datasets[2025] = df_2025

print("2025 columns standardized successfully!")

print("\nUpdated columns:")
print(df_2025.columns.tolist())

print("\nDataset shape:", df_2025.shape)

print("\nFirst 5 records:")
display(df_2025.head())

2025 columns standardized successfully!

Updated columns:
['Date', 'Route', 'Time', 'Day', 'Location', 'Incident Code', 'Min Delay', 'Min Gap', 'Direction', 'Vehicle']

Dataset shape: (102257, 10)

First 5 records:

,Date,Route,Time,Day,Location,Incident Code,Min Delay,Min Gap,Direction,Vehicle
0,2025-01-01,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442
1,2025-01-01,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,NaN,0
2,2025-01-01,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,NaN,8546
3,2025-01-01,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693
4,2025-01-01,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801

In [55]:
df_2025 = datasets[2025].copy()

# Preserve original route information
df_2025['Route Original'] = df_2025['Route']

# Extract route number from the beginning of the text
df_2025['Route'] = (
    df_2025['Route']
    .astype('string')
    .str.extract(r'^(\d+)', expand=False)
)

# Check extraction results
print("Route standardization completed!")

print("\nMissing route numbers:",
      df_2025['Route'].isna().sum())

print("\nSample results:")
display(df_2025[['Route Original', 'Route']].head(10))

# Update dataset
datasets[2025] = df_2025

Route standardization completed!

Missing route numbers: 1650

Sample results:

        Route Original Route
0     102 MARKHAM ROAD   102
1        65 PARLIAMENT    65
2              64 MAIN    64
3  100 FLEMINGDON PARK   100
4     34 EGLINTON EAST    34
5            320 YONGE   320
6         307 BATHURST   307
7            320 YONGE   320
8        112 WEST MALL   112
9        39 FINCH EAST    39

In [56]:
df_2025 = datasets[2025]

# Find records where route extraction failed
missing_routes = df_2025[
    df_2025['Route'].isna()
]

print("Total missing route numbers:", len(missing_routes))

print("\nMost common original route values:")
print(
    missing_routes['Route Original']
    .value_counts(dropna=False)
    .head(20) #??
)

print("\nSample records:")
display(
    missing_routes[
        ['Date', 'Route Original', 'Route']
    ].head(10)
)

Total missing route numbers: 1650

Most common original route values:
Route Original
NaN                   1241
LINE 1 SHUTTLE          65
LINE 2 SHUTTLE          52
YU                      27
RAD                     25
SRT                     24
SHUTTLE BUS             23
BD                      18
TRAINING BUS            17
A                       12
OTC                     10
LINE 2 SHUTTLE BUS       9
FLEET VEHICLE            8
TBM                      6
OTC TRAINING BUS         5
RAD 600                  5
OTC BUS                  5
LINE 2                   4
LINE 1 SHUTTLE BUS       4
FLEET                    4
Name: count, dtype: int64

Sample records:

          Date Route Original Route
59  2025-01-01            NaN  <NA>
77  2025-01-01            NaN  <NA>
83  2025-01-02            NaN  <NA>
108 2025-01-02            NaN  <NA>
190 2025-01-02            NaN  <NA>
257 2025-01-03            NaN  <NA>
409 2025-01-04            NaN  <NA>
430 2025-01-05            NaN  <NA>
433 2025-01-05            RAD  <NA>
439 2025-01-05            NaN  <NA>

In [57]:
df_2025 = datasets[2025].copy()

# Preserve numeric routes and recover non-numeric routes
df_2025['Route'] = df_2025['Route'].fillna(
    df_2025['Route Original'].astype('string').str.strip()
)

# Standardize route formatting
df_2025['Route'] = df_2025['Route'].str.title()

print("Route cleaning completed!")

print("\nRemaining missing routes:",
      df_2025['Route'].isna().sum())

print("\nSample non-numeric routes:")
display(
    df_2025[
        df_2025['Route'].str.contains(
            '[A-Z]', na=False
        )
    ][['Route Original', 'Route']].head(10)
)

Route cleaning completed!

Remaining missing routes: 1241

Sample non-numeric routes:

              Route Original                   Route
433                      RAD                     Rad
1317                     RAD                     Rad
1323                     RAD                     Rad
1975          LINE 1 SHUTTLE          Line 1 Shuttle
2136             SHUTTLE BUS             Shuttle Bus
2683                   FLEET                   Fleet
2756                     RAD                     Rad
3098          LINE 1 SHUTTLE          Line 1 Shuttle
3103          LINE 1 SHUTTLE          Line 1 Shuttle
3104  LINE 1 SHUTTLE (600 RA  Line 1 Shuttle (600 Ra

In [58]:
# Keep records from 2025 and 2026 seperated
df_2025 = df_2025[
    df_2025['Date'].dt.year == 2025
].copy()

df_2026 = df_2025[
    df_2025['Date'].dt.year == 2026
].copy()

# Reset index
df_2025.reset_index(drop=True, inplace=True)
df_2026.reset_index(drop=True, inplace=True)

# Update dataset
datasets[2025] = df_2025
datasets[2026] = df_2026

print("2025 and 2026 datasets seperated successfully!")

# print("\nRemaining rows:", df_2025.shape[0])
# print("Remaining columns:", df_2025.shape[1])

# print("\nDate range:")
# print("From:", df_2025['Date'].min())
# print("To:", df_2025['Date'].max())

2025 and 2026 datasets seperated successfully!

In [59]:
# Create a list to store datasets
all_datasets = []

for year, df in datasets.items():

    # Create a copy to preserve the original data
    temp_df = df.copy()

    # Add year column
    temp_df['Year'] = year

    # Add dataset to the list
    all_datasets.append(temp_df)

# Combine all datasets
df_combined = pd.concat(
    all_datasets,
    ignore_index=True,
    sort=False
)

# Display integration results
print("Data integration completed successfully!")

print("\nTotal rows:", df_combined.shape[0])
print("Total columns:", df_combined.shape[1])

print("\nRecords by year:")
print(df_combined['Year'].value_counts().sort_index())

print("\nCombined columns:")
print(df_combined.columns.tolist())

Data integration completed successfully!

Total rows: 316006
Total columns: 13

Records by year:
Year
2020    36151
2021    42269
2022    58707
2023    56207
2024    59643
2025    63029
Name: count, dtype: int64

Combined columns:
['Route', 'Time', 'Day', 'Location', 'Incident', 'Direction', 'Vehicle', 'Date', 'Min Delay', 'Min Gap', 'Year', 'Incident Code', 'Route Original']

# **4. Missing Values Handling**

In [60]:
# Count missing values in each column
missing_count = df_combined.isnull().sum()

# Calculate missing percentages
missing_percentage = (
    df_combined.isnull().mean() * 100
).round(2)

# Create missing values summary
missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Percentage (%)': missing_percentage
})

# Sort by highest missing percentage
missing_summary = missing_summary.sort_values(
    by='Missing Percentage (%)',
    ascending=False
)

print("Missing Values Analysis")
print("Total records:", len(df_combined))

display(missing_summary)

Missing Values Analysis
Total records: 316006

                Missing Count  Missing Percentage (%)
Route Original         253734                   80.29
Incident Code          252977                   80.05
Incident                63029                   19.95
Direction               51069                   16.16
Route                    2651                    0.84
Vehicle                  2259                    0.71
Min Delay                  55                    0.02
Min Gap                    71                    0.02
Location                   18                    0.01
Time                        0                    0.00
Day                         0                    0.00
Date                        0                    0.00
Year                        0                    0.00

In [61]:
# Select important columns
columns_to_check = [
    'Route',
    'Direction',
    'Vehicle',
    'Min Delay',
    'Min Gap',
    'Location'
]

# Calculate missing values for each year
missing_by_year = (
    df_combined
    .groupby('Year')[columns_to_check]
    .apply(lambda x: x.isnull().sum())
)

print("Missing Values by Year:")
display(missing_by_year)

# Calculate missing percentages by year
missing_percentage_by_year = (
    df_combined
    .groupby('Year')[columns_to_check]
    .apply(lambda x: (x.isnull().mean() * 100).round(2))
)

print("\nMissing Percentages by Year:")
display(missing_percentage_by_year)

Missing Values by Year:

      Route  Direction  Vehicle  Min Delay  Min Gap  Location
Year
2020     78       2518     2259         55       71        18
2021    240       7304        0          0        0         0
2022    384      10480        0          0        0         0
2023    570       9540        0          0        0         0
2024    622       9531        0          0        0         0
2025    757      11696        0          0        0         0

Missing Percentages by Year:

      Route  Direction  Vehicle  Min Delay  Min Gap  Location
Year
2020   0.22       6.97     6.25       0.15      0.2      0.05
2021   0.57      17.28     0.00       0.00      0.0      0.00
2022   0.65      17.85     0.00       0.00      0.0      0.00
2023   1.01      16.97     0.00       0.00      0.0      0.00
2024   1.04      15.98     0.00       0.00      0.0      0.00
2025   1.20      18.56     0.00       0.00      0.0      0.00

In [62]:
df_2020 = df_combined[
    df_combined['Year'] == 2020
].copy()

# Check missing values
print("Missing Min Delay:", df_2020['Min Delay'].isna().sum())

print("Missing Min Gap:", df_2020['Min Gap'].isna().sum())

# Check overlap between missing values
print("\nBoth Delay and Gap missing:",
      (
          df_2020['Min Delay'].isna() &
          df_2020['Min Gap'].isna()
      ).sum())

# Display records with missing Delay or Gap
missing_delay_gap = df_2020[
    df_2020['Min Delay'].isna() |
    df_2020['Min Gap'].isna()
]

print("\nTotal affected records:", len(missing_delay_gap))

display(
    missing_delay_gap[
        ['Date', 'Route', 'Incident', 'Min Delay', 'Min Gap']
    ].head(15)
)

Missing Min Delay: 55
Missing Min Gap: 71

Both Delay and Gap missing: 46

Total affected records: 80

           Date  Route                          Incident  Min Delay  Min Gap
106  2020-01-02   15.0                     Investigation       10.0      NaN
360  2020-01-04   11.0                         Diversion        NaN      NaN
710  2020-01-07  939.0                     Investigation       11.0      NaN
1784 2020-01-15   39.0                         Diversion        NaN      NaN
1847 2020-01-16   91.0  Late Leaving Garage - Mechanical        9.0      NaN
1874 2020-01-16  100.0  Late Leaving Garage - Management        9.0      NaN
1875 2020-01-16  954.0  Late Leaving Garage - Mechanical       16.0      NaN
2030 2020-01-17   79.0    Late Leaving Garage - Operator        NaN     14.0
2037 2020-01-17  924.0  Late Leaving Garage - Mechanical        NaN      9.0
2038 2020-01-17   94.0  Late Leaving Garage - Mechanical        NaN     15.0
2511 2020-01-20  110.0                         Diversion        NaN      NaN
3127 2020-01-23  939.0                     General Delay        NaN      NaN
3268 2020-01-24  953.0                Utilized Off Route        NaN      1.0
3680 2020-01-27  939.0                         Diversion        NaN      NaN
4090 2020-01-30  939.0                        Mechanical       15.0      NaN

In [63]:
# Preserve the combined dataset before cleaning
df_before_cleaning = df_combined.copy()

# Create a working copy
df_cleaned = df_combined.copy()

# Count records before cleaning
rows_before = len(df_cleaned)

# Remove records missing Delay or Gap
df_cleaned = df_cleaned.dropna(
    subset=['Min Delay', 'Min Gap']
).copy()

# Reset index
df_cleaned.reset_index(drop=True, inplace=True)

# Count records after cleaning
rows_after = len(df_cleaned)

print("Missing Delay and Gap handling completed!")

print("\nRecords before cleaning:", rows_before)
print("Records after cleaning:", rows_after)
print("Removed records:", rows_before - rows_after)

print("\nRemaining missing values:")
print(df_cleaned[['Min Delay', 'Min Gap']].isna().sum())

Missing Delay and Gap handling completed!

Records before cleaning: 316006
Records after cleaning: 315926
Removed records: 80

Remaining missing values:
Min Delay    0
Min Gap      0
dtype: int64

In [64]:
# Columns to clean
categorical_columns = [
    'Route',
    'Direction',
    'Vehicle',
    'Location'
]

# Count missing values before cleaning
print("Missing values before cleaning:")
print(df_cleaned[categorical_columns].isna().sum())

# Replace missing values with Unknown
for col in categorical_columns:
    df_cleaned[col] = (
        df_cleaned[col]
        .astype('string')
        .fillna('Unknown')
    )

# Check results
print("\nMissing values after cleaning:")
print(df_cleaned[categorical_columns].isna().sum())

print("\nDataset shape:", df_cleaned.shape)

Missing values before cleaning:
Route         2651
Direction    51067
Vehicle       2251
Location        18
dtype: int64

Missing values after cleaning:
Route        0
Direction    0
Vehicle      0
Location     0
dtype: int64

Dataset shape: (315926, 13)

# **5. Duplicate Detection & Removal**

In [65]:
print("Total records:", len(df_cleaned))

# Count exact duplicate rows
duplicates = df_cleaned.duplicated().sum()

print("Total duplicate records:", duplicates)

# Display sample duplicates
print("\nSample duplicate records:")

display(
    df_cleaned[
        df_cleaned.duplicated(keep=False)
    ].head(10)
)

Total records: 315926
Total duplicate records: 1232

Sample duplicate records:

,Route,Time,Day,Location,Incident,Direction,Vehicle,Date,Min Delay,Min Gap,Year,Incident Code,Route Original
1169,84.0,05:15:00,Saturday,Sheppard Stn.,Late Leaving Garage - Operator,W/B,3315.0,2020-01-11,1.0,30.0,2020,NaN,NaN
1170,84.0,05:15:00,Saturday,Sheppard Stn.,Late Leaving Garage - Operator,W/B,3315.0,2020-01-11,1.0,30.0,2020,NaN,NaN
1705,143.0,08:00:00,Wednesday,Entire route,General Delay,E/B,Unknown,2020-01-15,15.0,30.0,2020,NaN,NaN
1706,143.0,08:00:00,Wednesday,Entire route,General Delay,E/B,Unknown,2020-01-15,15.0,30.0,2020,NaN,NaN
1785,90.0,20:25:00,Wednesday,St. Clair West Stn,Utilized Off Route,N/B,8166.0,2020-01-15,9.0,18.0,2020,NaN,NaN
1786,90.0,20:25:00,Wednesday,St. Clair West Stn,Utilized Off Route,N/B,8166.0,2020-01-15,9.0,18.0,2020,NaN,NaN
2815,89.0,06:20:00,Wednesday,Keele Stn,Utilized Off Route,N/B,1043.0,2020-01-22,7.0,14.0,2020,NaN,NaN
2816,89.0,06:20:00,Wednesday,Keele Stn,Utilized Off Route,N/B,1043.0,2020-01-22,7.0,14.0,2020,NaN,NaN
3070,119.0,06:40:00,Thursday,Wilson Station,Late Leaving Garage - Operator,W/B,3226.0,2020-01-23,20.0,40.0,2020,NaN,NaN
3071,119.0,06:40:00,Thursday,Wilson Station,Late Leaving Garage - Operator,W/B,3226.0,2020-01-23,20.0,40.0,2020,NaN,NaN

In [66]:
# Identify exact duplicates
df_cleaned['Is Duplicate'] = df_cleaned.duplicated()

# Count duplicates by year
duplicates_by_year = (
    df_cleaned.groupby('Year')['Is Duplicate']
    .sum()
)

# Calculate duplicate percentages
duplicate_percentage = (
    df_cleaned.groupby('Year')['Is Duplicate']
    .mean() * 100
).round(2)

# Create summary table
duplicate_summary = pd.DataFrame({
    'Duplicate Count': duplicates_by_year,
    'Duplicate Percentage (%)': duplicate_percentage
})

print("Duplicate Analysis by Year:")
display(duplicate_summary)

# Remove temporary column
df_cleaned.drop(columns=['Is Duplicate'], inplace=True)

Duplicate Analysis by Year:

      Duplicate Count  Duplicate Percentage (%)
Year
2020               94                      0.26
2021              189                      0.45
2022              367                      0.63
2023              200                      0.36
2024              198                      0.33
2025              184                      0.29

In [67]:
# Save a backup before removing duplicates
df_before_duplicates = df_cleaned.copy()

# Count records before
rows_before = len(df_cleaned)

# Remove exact duplicates
df_cleaned = df_cleaned.drop_duplicates().copy()

# Reset index
df_cleaned.reset_index(drop=True, inplace=True)

# Count records after
rows_after = len(df_cleaned)

print("Duplicate Removal Completed!")

print("\nRecords before:", rows_before)
print("Records after:", rows_after)
print("Duplicates removed:", rows_before - rows_after)

print("\nRemaining duplicates:",
      df_cleaned.duplicated().sum())

Duplicate Removal Completed!

Records before: 315926
Records after: 314694
Duplicates removed: 1232

Remaining duplicates: 0

# **6. Data Type & Time Standardization**

In [68]:
print("Dataset Information:")
df_cleaned.info()

print("\nData Types:")
print(df_cleaned.dtypes)

print("\nSample Records:")
display(df_cleaned.head())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314694 entries, 0 to 314693
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Route           314694 non-null  string
 1   Time            314694 non-null  object
 2   Day             314694 non-null  object
 3   Location        314694 non-null  string
 4   Incident        251849 non-null  object
 5   Direction       314694 non-null  string
 6   Vehicle         314694 non-null  string
 7   Date            314694 non-null  datetime64[ns]
 8   Min Delay       314694 non-null  float64
 9   Min Gap         314694 non-null  float64
 10  Year            314694 non-null  int64
 11  Incident Code   62845 non-null   object
 12  Route Original  62088 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5), string(4)
memory usage: 31.2+ MB

Data Types:
Route             string[python]
Time                      object
Day                       object
Location          string[python]
Incident                  object
Direction         string[python]
Vehicle           string[python]
Date              datetime64[ns]
Min Delay                float64
Min Gap                  float64
Year                       int64
Incident Code             object
Route Original            object
dtype: object

Sample Records:

,Route,Time,Day,Location,Incident,Direction,Vehicle,Date,Min Delay,Min Gap,Year,Incident Code,Route Original
0,94.0,00:01:00,Wednesday,Ossington station and Castle Frank Station,General Delay,B/W,Unknown,2020-01-01,10.0,20.0,2020,NaN,NaN
1,320.0,01:31:00,Wednesday,Yonge @ Queen,Diversion,B/W,Unknown,2020-01-01,1.0,1.0,2020,NaN,NaN
2,29.0,01:37:00,Wednesday,Dufferin loop,Mechanical,N/B,9028.0,2020-01-01,8.0,14.0,2020,NaN,NaN
3,102.0,01:40:00,Wednesday,Warden station,Mechanical,N/B,8504.0,2020-01-01,11.0,22.0,2020,NaN,NaN
4,68.0,01:42:00,Wednesday,Warden Station,Mechanical,N/B,8721.0,2020-01-01,8.0,23.0,2020,NaN,NaN

In [69]:
import re

# Save backup
df_before_formatting = df_cleaned.copy()

# Function to standardize identifiers
def standardize_identifier(value):

    value = str(value).strip()

    # Remove .0 only from numeric identifiers
    if re.fullmatch(r'\d+\.0', value):
        value = value[:-2]

    return value

# Apply standardization
df_cleaned['Route'] = (
    df_cleaned['Route']
    .apply(standardize_identifier)
    .astype('string')
)

df_cleaned['Vehicle'] = (
    df_cleaned['Vehicle']
    .apply(standardize_identifier)
    .astype('string')
)

print("Route and Vehicle Formatting Completed!")

print("\nSample Routes:")
print(df_cleaned['Route'].head(10).tolist())

print("\nSample Vehicles:")
print(df_cleaned['Vehicle'].head(10).tolist())

print("\nDataset Shape:", df_cleaned.shape)

Route and Vehicle Formatting Completed!

Sample Routes:
['94', '320', '29', '102', '68', '53', '76', '76', '89', '300']

Sample Vehicles:
['Unknown', 'Unknown', '9028', '8504', '8721', '3436', '7966', '7966', '1111', '8003']

Dataset Shape: (314694, 13)

In [70]:
# Check types stored in Time column
print("Time Value Types:")
print(df_cleaned['Time'].apply(type).value_counts())

# Convert time values for validation
time_values = pd.to_datetime(
    df_cleaned['Time'].astype(str),
    format='%H:%M:%S',
    errors='coerce'
)

# Count invalid times
invalid_times = time_values.isna().sum()

print("\nInvalid Time Values:", invalid_times)

# Display examples of invalid times
print("\nSample Invalid Times:")
display(
    df_cleaned.loc[
        time_values.isna(),
        ['Year', 'Date', 'Time']
    ].head(15)
)

print("\nTotal Records:", len(df_cleaned))

Time Value Types:
Time
<class 'str'>                  289962
<class 'datetime.time'>         24727
<class 'datetime.datetime'>         5
Name: count, dtype: int64

Invalid Time Values: 289967

Sample Invalid Times:

       Year       Date                 Time
2616   2020 2020-01-20  2020-01-20 00:00:00
7239   2020 2020-02-21  2020-02-21 00:00:00
13785  2020 2020-04-14  2020-04-14 00:00:00
22424  2020 2020-06-29  2020-06-29 00:00:00
23375  2020 2020-07-12  2020-07-12 00:00:00
24732  2020 2020-08-01                02:18
24733  2020 2020-08-01                03:17
24734  2020 2020-08-01                03:21
24735  2020 2020-08-01                03:26
24736  2020 2020-08-01                03:27
24737  2020 2020-08-01                06:28
24738  2020 2020-08-01                08:00
24739  2020 2020-08-01                08:02
24740  2020 2020-08-01                08:13
24741  2020 2020-08-01                08:28

Total Records: 314694

In [71]:
import datetime

# Save backup
df_before_time_cleaning = df_cleaned.copy()

def standardize_time(value):

    # Handle datetime objects
    if isinstance(value, datetime.datetime):
        return value.strftime('%H:%M:%S')

    # Handle time objects
    if isinstance(value, datetime.time):
        return value.strftime('%H:%M:%S')

    # Handle string values
    value = str(value).strip()

    # HH:MM -> HH:MM:SS
    if len(value) == 5 and value.count(':') == 1:
        value += ':00'

    # Validate time
    try:
        return datetime.datetime.strptime(
            value, '%H:%M:%S'
        ).strftime('%H:%M:%S')

    except ValueError:
        return pd.NA

# Apply standardization
df_cleaned['Time'] = (
    df_cleaned['Time']
    .apply(standardize_time)
    .astype('string')
)

print("Time Standardization Completed!")

print("\nMissing/Invalid Times:",
      df_cleaned['Time'].isna().sum())

print("\nSample Times:")
print(df_cleaned['Time'].head(10).tolist())

print("\nDataset Shape:", df_cleaned.shape)

Time Standardization Completed!

Missing/Invalid Times: 0

Sample Times:
['00:01:00', '01:31:00', '01:37:00', '01:40:00', '01:42:00', '01:46:00', '03:10:00', '03:12:00', '03:12:00', '04:15:00']

Dataset Shape: (314694, 13)

# **7. Outlier Detection**

In [72]:
# Descriptive statistics
print("Descriptive Statistics:")
display(df_cleaned[['Min Delay', 'Min Gap']].describe())

# Check negative and zero values
for col in ['Min Delay', 'Min Gap']:

    print(f"\n{col}:")

    print("Negative values:",
          (df_cleaned[col] < 0).sum())

    print("Zero values:",
          (df_cleaned[col] == 0).sum())

    # Calculate IQR
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Count outliers
    outliers = (
        (df_cleaned[col] < lower_bound) |
        (df_cleaned[col] > upper_bound)
    ).sum()

    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Potential Outliers:", outliers)

# Display largest delays
print("\nTop 10 Largest Delays:")
display(
    df_cleaned.nlargest(10, 'Min Delay')[
        ['Year', 'Date', 'Route', 'Incident',
         'Min Delay', 'Min Gap']
    ]
)

Descriptive Statistics:

           Min Delay        Min Gap
count  314694.000000  314694.000000
mean       20.323686      32.647429
std        51.717644      53.495755
min         0.000000       0.000000
25%         8.000000      16.000000
50%        11.000000      22.000000
75%        20.000000      38.000000
max      1214.000000    1234.000000

Min Delay:
Negative values: 0
Zero values: 25835
Lower Bound: -10.0
Upper Bound: 38.0
Potential Outliers: 16218

Min Gap:
Negative values: 0
Zero values: 26896
Lower Bound: -17.0
Upper Bound: 71.0
Potential Outliers: 13483

Top 10 Largest Delays:

       Year       Date Route   Incident  Min Delay  Min Gap
17495  2020 2020-05-12    41  Diversion     1214.0   1226.0
18769  2020 2020-05-25   131  Diversion     1206.0   1206.0
6408   2020 2020-02-15    80  Diversion     1204.0   1234.0
6070   2020 2020-02-13    72  Diversion     1186.0   1204.0
18570  2020 2020-05-23   131  Diversion     1135.0   1153.0
11765  2020 2020-03-29    40  Diversion     1125.0   1153.0
21438  2020 2020-06-20    75  Diversion     1114.0   1129.0
19238  2020 2020-05-29    84  Diversion     1030.0   1040.0
1379   2020 2020-01-13    75  Diversion      999.0    999.0
1512   2020 2020-01-14    75  Diversion      999.0    999.0

In [73]:
# Define extreme delays as more than 180 minutes
extreme_delays = df_cleaned[
    df_cleaned['Min Delay'] > 180
]

# Count extreme delays by year
extreme_by_year = (
    extreme_delays.groupby('Year')
    .size()
    .reindex(sorted(df_cleaned['Year'].unique()), fill_value=0)
)

print("Extreme Delays (>180 minutes) by Year:")
display(extreme_by_year.to_frame('Extreme Delay Count'))

# Show maximum delay per year
print("\nMaximum Delay by Year:")
display(
    df_cleaned.groupby('Year')['Min Delay']
    .max()
    .to_frame('Maximum Delay')
)

# Most common incidents among extreme delays
print("\nTop Incidents for Extreme Delays:")
display(
    extreme_delays['Incident']
    .value_counts()
    .head(10)
)

print("\nTotal Extreme Delays:", len(extreme_delays))

Extreme Delays (>180 minutes) by Year:

      Extreme Delay Count
Year
2020                  503
2021                  378
2022                  710
2023                  680
2024                  922
2025                  862

Maximum Delay by Year:

      Maximum Delay
Year
2020         1214.0
2021          999.0
2022          999.0
2023          998.0
2024          975.0
2025          999.0

Top Incidents for Extreme Delays:

Incident
Diversion                           2553
General Delay                        301
Road Blocked - NON-TTC Collision     211
Investigation                         37
Held By                               32
Security                              16
Emergency Services                    12
Operations - Operator                 10
Utilized Off Route                     5
Collision - TTC                        5
Name: count, dtype: int64

Total Extreme Delays: 4055

In [74]:
# Count specific high delay values
print("High Delay Value Frequencies:")

high_delay_counts = (
    df_cleaned[
        df_cleaned['Min Delay'] >= 900
    ]['Min Delay']
    .value_counts()
    .sort_index()
)

display(high_delay_counts.to_frame('Count'))

# Check 999 values by year
print("\n999-Minute Delays by Year:")

delay_999 = df_cleaned[
    df_cleaned['Min Delay'] == 999
]

display(
    delay_999.groupby('Year')
    .size()
    .to_frame('Count')
)

# Show sample records
print("\nSample 999-Minute Delays:")

display(
    delay_999[
        ['Year', 'Date', 'Route', 'Incident',
         'Incident Code', 'Min Delay', 'Min Gap']
    ].head(15)
)

print("\nTotal 999-Minute Delays:", len(delay_999))

High Delay Value Frequencies:

           Count
Min Delay
900.0         10
901.0          1
903.0          2
905.0          1
906.0          1
...          ...
1135.0         1
1186.0         1
1204.0         1
1206.0         1
1214.0         1

[62 rows x 1 columns]

999-Minute Delays by Year:

      Count
Year
2020     62
2021      2
2022      4
2025      1

Sample 999-Minute Delays:

      Year       Date Route   Incident Incident Code  Min Delay  Min Gap
1379  2020 2020-01-13    75  Diversion           NaN      999.0    999.0
1512  2020 2020-01-14    75  Diversion           NaN      999.0    999.0
1679  2020 2020-01-15    75  Diversion           NaN      999.0    999.0
1846  2020 2020-01-16    75  Diversion           NaN      999.0    999.0
2018  2020 2020-01-17    75  Diversion           NaN      999.0    999.0
2472  2020 2020-01-20    75  Diversion           NaN      999.0    999.0
2625  2020 2020-01-21    75  Diversion           NaN      999.0    999.0
2773  2020 2020-01-22    75  Diversion           NaN      999.0    999.0
5658  2020 2020-02-10    34  Diversion           NaN      999.0    999.0
5775  2020 2020-02-11    34  Diversion           NaN      999.0    999.0
5900  2020 2020-02-12    34  Diversion           NaN      999.0    999.0
6154  2020 2020-02-13    34  Diversion           NaN      999.0    999.0
6562  2020 2020-02-17    34  Diversion           NaN      999.0    999.0
6620  2020 2020-02-18    34  Diversion           NaN      999.0    999.0
6839  2020 2020-02-19    34  Diversion           NaN      999.0    999.0

Total 999-Minute Delays: 69

In [75]:
# Count 999 in each column
delay_999 = (df_cleaned['Min Delay'] == 999).sum()
gap_999 = (df_cleaned['Min Gap'] == 999).sum()

# Count records where both equal 999
both_999 = (
    (df_cleaned['Min Delay'] == 999) &
    (df_cleaned['Min Gap'] == 999)
).sum()

print("Min Delay = 999:", delay_999)
print("Min Gap = 999:", gap_999)
print("Both = 999:", both_999)

# Check incidents associated with 999
suspicious_records = df_cleaned[
    (df_cleaned['Min Delay'] == 999) |
    (df_cleaned['Min Gap'] == 999)
]

print("\nIncidents associated with 999:")
display(
    suspicious_records.groupby(
        ['Year', 'Incident'],
        dropna=False
    ).size().to_frame('Count')
)

print("\nTotal affected records:", len(suspicious_records))

Min Delay = 999: 69
Min Gap = 999: 67
Both = 999: 66

Incidents associated with 999:

                    Count
Year Incident
2020 Diversion         62
2021 General Delay      2
2022 Diversion          5
2025 NaN                1

Total affected records: 70

In [76]:
# Save backup
df_before_outlier_handling = df_cleaned.copy()

# Flag records containing 999
df_cleaned['Suspicious_999'] = (
    (df_cleaned['Min Delay'] == 999) |
    (df_cleaned['Min Gap'] == 999)
)

print("Suspicious Value Flagging Completed!")

print("\nFlagged records:",
      df_cleaned['Suspicious_999'].sum())

print("\nUnflagged records:",
      (~df_cleaned['Suspicious_999']).sum())

print("\nDataset Shape:", df_cleaned.shape)

print("\nFlag Distribution:")
display(
    df_cleaned['Suspicious_999']
    .value_counts()
    .to_frame('Count')
)

Suspicious Value Flagging Completed!

Flagged records: 70

Unflagged records: 314624

Dataset Shape: (314694, 14)

Flag Distribution:

                 Count
Suspicious_999
False           314624
True                70

# **8. Final Data Validation**

In [77]:
print("FINAL DATA VALIDATION")
print("=" * 40)

# Dataset dimensions
print("\nTotal Records:", len(df_cleaned))
print("Total Columns:", len(df_cleaned.columns))

# Check duplicates (excluding the flag column)
print("\nDuplicate Records:",
      df_cleaned.drop(columns=['Suspicious_999']).duplicated().sum())

# Check important missing values
important_columns = [
    'Date', 'Time', 'Year',
    'Min Delay', 'Min Gap',
    'Route', 'Direction', 'Vehicle', 'Location'
]

print("\nMissing Values:")
print(df_cleaned[important_columns].isna().sum())

# Check negative delay values
print("\nNegative Delays:",
      (df_cleaned['Min Delay'] < 0).sum())

print("Negative Gaps:",
      (df_cleaned['Min Gap'] < 0).sum())

# Check year range
print("\nYears:",
      sorted(df_cleaned['Year'].unique()))

# Verify Date matches Year
year_mismatch = (
    df_cleaned['Date'].dt.year != df_cleaned['Year']
).sum()

print("Date-Year Mismatches:", year_mismatch)

# Check suspicious values
print("\nFlagged 999 Values:",
      df_cleaned['Suspicious_999'].sum())

# Final dataset shape
print("\nFinal Dataset Shape:", df_cleaned.shape)

FINAL DATA VALIDATION
========================================

Total Records: 314694
Total Columns: 14

Duplicate Records: 0

Missing Values:
Date         0
Time         0
Year         0
Min Delay    0
Min Gap      0
Route        0
Direction    0
Vehicle      0
Location     0
dtype: int64

Negative Delays: 0
Negative Gaps: 0

Years: [np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
Date-Year Mismatches: 0

Flagged 999 Values: 70

Final Dataset Shape: (314694, 14)

# **9. Export Cleaned Dataset**

In [78]:
# Save cleaned dataset as CSV
df_cleaned.to_csv(
    'TTC_Bus_Delays_Cleaned_2020_2026.csv',
    index=False
)

print("Dataset exported successfully!")

print("Final Shape:", df_cleaned.shape)

# # Download CSV file
# from google.colab import files

# files.download('TTC_Bus_Delays_Cleaned_2020_2026.csv')

Dataset exported successfully!
Final Shape: (314694, 14)